project:
  type: website
  output-dir: _site

website:
  site-url: https://ajmmedina.github.io/clases-calculo-diferencial/
  title: "CÃ¡lculo Diferencial"
  navbar:
    left:
      - href: index.qmd
        text: Inicio

format:
  revealjs:
    theme: simple
    chalkboard: true
    width: 1600
    height: 900
    self-contained: false # Importante: En web no necesitas self-contained